// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Radar.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Radar.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(RadarDbContext))]
    partial class RadarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("radar")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Radar.Dominio.Monitoramento", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADO_EM");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXCLUIDO_EM");

                    b.Property<decimal?>("MenorPrecoAtual")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("MENOR_PRECO_ATUAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.Property<DateTimeOffset?>("PausadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAUSADO_EM");

                    b.Property<decimal>("PrecoAlvo")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_ALVO");

                    b.Property<decimal>("PrecoInicial")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_INICIAL");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<Guid?>("ProdutoVarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_VARIANTE_ID");

                    b.Property<DateTimeOffset?>("ProximaVerificacaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PROXIMA_VERIFICACAO_EM");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<long?>("UltimaObservacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("ULTIMA_OBSERVACAO_ID");

                    b.Property<Guid?>("UltimaOfertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ULTIMA_OFERTA_ID");

                    b.Property<DateTimeOffset?>("UltimaVerificacaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ULTIMA_VERIFICACAO_EM");

                    b.Property<DateTimeOffset?>("UltimoAlertaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ULTIMO_ALERTA_EM");

                    b.Property<decimal?>("UltimoPrecoAlertado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("ULTIMO_PRECO_ALERTADO");

                    b.HasKey("Id");

                    b.ToTable("MONITORAMENTO", "radar", t =>
                        {
                          t.HasCheckConstraint("CK_MONITORAMENTO_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_MONITORAMENTO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_MONITORAMENTO_MENOR_PRECO_ATUAL", "\"MENOR_PRECO_ATUAL\" >= 0 AND \"MENOR_PRECO_ATUAL\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_MONITORAMENTO_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_MONITORAMENTO_PRECO_ALVO", "\"PRECO_ALVO\" >= 0.01 AND \"PRECO_ALVO\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_MONITORAMENTO_PRECO_INICIAL", "\"PRECO_INICIAL\" >= 0.01 AND \"PRECO_INICIAL\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_MONITORAMENTO_PRODUTO_ID", "\"PRODUTO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_MONITORAMENTO_PRODUTO_VARIANTE_ID", "\"PRODUTO_VARIANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_MONITORAMENTO_STATUS", "\"STATUS\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_MONITORAMENTO_ULTIMA_OBSERVACAO_ID", "\"ULTIMA_OBSERVACAO_ID\" >= 1 AND \"ULTIMA_OBSERVACAO_ID\" <= 9223372036854775807");

                            t.HasCheckConstraint("CK_MONITORAMENTO_ULTIMA_OFERTA_ID", "\"ULTIMA_OFERTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_MONITORAMENTO_ULTIMO_PRECO_ALERTADO", "\"ULTIMO_PRECO_ALERTADO\" >= 0 AND \"ULTIMO_PRECO_ALERTADO\" <= 999999999999.99");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Radar.Dominio.Oportunidade", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("DetectadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DETECTADA_EM");

                    b.Property<decimal?>("EconomiaDesdeCriacao")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("ECONOMIA_DESDE_CRIACAO");

                    b.Property<DateTimeOffset?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXPIRA_EM");

                    b.Property<Guid>("MonitoramentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("MONITORAMENTO_ID");

                    b.Property<Guid>("OfertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("OFERTA_ID");

                    b.Property<long>("OfertaObservacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("OFERTA_OBSERVACAO_ID");

                    b.Property<string>("OfertaSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("OFERTA_SNAPSHOT");

                    b.Property<decimal?>("PercentualReducao")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("PERCENTUAL_REDUCAO");

                    b.Property<decimal>("PrecoAlvo")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_ALVO");

                    b.Property<decimal>("PrecoObservado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_OBSERVADO");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<DateTimeOffset?>("VisualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VISUALIZADA_EM");

                    b.HasKey("Id");

                    b.HasIndex("MonitoramentoId", "OfertaObservacaoId")
                        .IsUnique();

                    b.ToTable("OPORTUNIDADE", "radar", t =>
                        {
                          t.HasCheckConstraint("CK_OPORTUNIDADE_ECONOMIA_DESDE_CRIACAO", "\"ECONOMIA_DESDE_CRIACAO\" >= -999999999999.99 AND \"ECONOMIA_DESDE_CRIACAO\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_MONITORAMENTO_ID", "\"MONITORAMENTO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_OFERTA_ID", "\"OFERTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_OFERTA_OBSERVACAO_ID", "\"OFERTA_OBSERVACAO_ID\" >= 1 AND \"OFERTA_OBSERVACAO_ID\" <= 9223372036854775807");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_OFERTA_SNAPSHOT", "jsonb_typeof(\"OFERTA_SNAPSHOT\") = 'object'");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_PERCENTUAL_REDUCAO", "\"PERCENTUAL_REDUCAO\" >= -999 AND \"PERCENTUAL_REDUCAO\" <= 100");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_PRECO_ALVO", "\"PRECO_ALVO\" >= 0.01 AND \"PRECO_ALVO\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_PRECO_OBSERVADO", "\"PRECO_OBSERVADO\" >= 0.01 AND \"PRECO_OBSERVADO\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_REGRA_10", "\"PRECO_OBSERVADO\" <= \"PRECO_ALVO\"");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_REGRA_11", "\"EXPIRA_EM\" IS NULL OR \"EXPIRA_EM\" > \"DETECTADA_EM\"");

                            t.HasCheckConstraint("CK_OPORTUNIDADE_STATUS", "\"STATUS\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Radar.Dominio.Oportunidade", b =>
                {
                  b.HasOne("Verum.Modules.Radar.Dominio.Monitoramento", "Monitoramento")
                        .WithMany("Oportunidades")
                        .HasForeignKey("MonitoramentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Monitoramento");
                });

            modelBuilder.Entity("Verum.Modules.Radar.Dominio.Monitoramento", b =>
                {
                  b.Navigation("Oportunidades");
                });
#pragma warning restore 612, 618
        }
    }
}
