// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Assinaturas.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Assinaturas.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(AssinaturasDbContext))]
    [Migration("20260926134537_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assinaturas")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.Assinatura", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<DateTimeOffset?>("CanceladaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CANCELADA_EM");

                    b.Property<DateTimeOffset?>("CancelamentoSolicitadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CANCELAMENTO_SOLICITADO_EM");

                    b.Property<Guid>("ClienteGatewayId")
                        .HasColumnType("uuid")
                        .HasColumnName("CLIENTE_GATEWAY_ID");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<short>("Gateway")
                        .HasColumnType("smallint")
                        .HasColumnName("GATEWAY");

                    b.Property<string>("IdentificadorExterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IDENTIFICADOR_EXTERNO");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("MOEDA")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("PeriodoIniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PERIODO_INICIADO_EM");

                    b.Property<DateTimeOffset?>("PeriodoTerminaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PERIODO_TERMINA_EM");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PLANO_ID");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorContratado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("VALOR_CONTRATADO");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.HasIndex("Gateway", "IdentificadorExterno")
                        .IsUnique();

                    b.HasIndex("ClienteGatewayId", "ContaId", "Gateway");

                    b.ToTable("ASSINATURA", "assinaturas", t =>
                        {
                          t.HasCheckConstraint("CK_ASSINATURA_CLIENTE_GATEWAY_ID", "\"CLIENTE_GATEWAY_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ASSINATURA_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ASSINATURA_GATEWAY", "\"GATEWAY\" IN (1)");

                            t.HasCheckConstraint("CK_ASSINATURA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ASSINATURA_IDENTIFICADOR_EXTERNO", "length(btrim(\"IDENTIFICADOR_EXTERNO\")) > 0");

                            t.HasCheckConstraint("CK_ASSINATURA_MOEDA", "length(btrim(\"MOEDA\")) > 0");

                            t.HasCheckConstraint("CK_ASSINATURA_PLANO_ID", "\"PLANO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ASSINATURA_STATUS", "\"STATUS\" IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_ASSINATURA_VALOR_CONTRATADO", "\"VALOR_CONTRATADO\" >= 0.01 AND \"VALOR_CONTRATADO\" <= 999999999999.99");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.ClienteGateway", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADO_EM");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<short>("Gateway")
                        .HasColumnType("smallint")
                        .HasColumnName("GATEWAY");

                    b.Property<string>("IdentificadorExterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IDENTIFICADOR_EXTERNO");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "Gateway")
                        .IsUnique();

                    b.HasIndex("Gateway", "IdentificadorExterno")
                        .IsUnique();

                    b.ToTable("CLIENTE_GATEWAY", "assinaturas", t =>
                        {
                          t.HasCheckConstraint("CK_CLIENTE_GATEWAY_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CLIENTE_GATEWAY_GATEWAY", "\"GATEWAY\" IN (1)");

                            t.HasCheckConstraint("CK_CLIENTE_GATEWAY_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CLIENTE_GATEWAY_IDENTIFICADOR_EXTERNO", "length(btrim(\"IDENTIFICADOR_EXTERNO\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.EventoGateway", b =>
                {
                  b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("CONTEUDO");

                    b.Property<short>("Gateway")
                        .HasColumnType("smallint")
                        .HasColumnName("GATEWAY");

                    b.Property<string>("IdentificadorExterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IDENTIFICADOR_EXTERNO");

                    b.Property<DateTimeOffset?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PROCESSADO_EM");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RECEBIDO_EM");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<short>("Tentativas")
                        .HasColumnType("smallint")
                        .HasColumnName("TENTATIVAS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("TIPO");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ULTIMO_ERRO");

                    b.HasKey("Id");

                    b.HasIndex("Gateway", "IdentificadorExterno")
                        .IsUnique();

                    b.ToTable("EVENTO_GATEWAY", "assinaturas", t =>
                        {
                          t.HasCheckConstraint("CK_EVENTO_GATEWAY_CONTEUDO", "jsonb_typeof(\"CONTEUDO\") = 'object'");

                            t.HasCheckConstraint("CK_EVENTO_GATEWAY_GATEWAY", "\"GATEWAY\" IN (1)");

                            t.HasCheckConstraint("CK_EVENTO_GATEWAY_IDENTIFICADOR_EXTERNO", "length(btrim(\"IDENTIFICADOR_EXTERNO\")) > 0");

                            t.HasCheckConstraint("CK_EVENTO_GATEWAY_STATUS", "\"STATUS\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_EVENTO_GATEWAY_TENTATIVAS", "\"TENTATIVAS\" >= 0 AND \"TENTATIVAS\" <= 32767");

                            t.HasCheckConstraint("CK_EVENTO_GATEWAY_TIPO", "length(btrim(\"TIPO\")) > 0");

                            t.HasCheckConstraint("CK_EVENTO_GATEWAY_ULTIMO_ERRO", "length(btrim(\"ULTIMO_ERRO\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.Pagamento", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid>("AssinaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ASSINATURA_ID");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADO_EM");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("IdentificadorExterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IDENTIFICADOR_EXTERNO");

                    b.Property<short?>("Metodo")
                        .HasColumnType("smallint")
                        .HasColumnName("METODO");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("MOEDA")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("PagoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAGO_EM");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("VALOR");

                    b.Property<DateTimeOffset?>("VencimentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VENCIMENTO_EM");

                    b.HasKey("Id");

                    b.HasIndex("AssinaturaId", "IdentificadorExterno")
                        .IsUnique();

                    b.ToTable("PAGAMENTO", "assinaturas", t =>
                        {
                          t.HasCheckConstraint("CK_PAGAMENTO_ASSINATURA_ID", "\"ASSINATURA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PAGAMENTO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PAGAMENTO_IDENTIFICADOR_EXTERNO", "length(btrim(\"IDENTIFICADOR_EXTERNO\")) > 0");

                            t.HasCheckConstraint("CK_PAGAMENTO_METODO", "\"METODO\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_PAGAMENTO_MOEDA", "length(btrim(\"MOEDA\")) > 0");

                            t.HasCheckConstraint("CK_PAGAMENTO_STATUS", "\"STATUS\" IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_PAGAMENTO_VALOR", "\"VALOR\" >= 0.01 AND \"VALOR\" <= 999999999999.99");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.Plano", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ATIVO");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADO_EM");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("MOEDA")
                        .IsFixedLength();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("NOME");

                    b.Property<string>("PacoteAcessoCodigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("PACOTE_ACESSO_CODIGO");

                    b.Property<short>("Periodicidade")
                        .HasColumnType("smallint")
                        .HasColumnName("PERIODICIDADE");

                    b.Property<decimal>("ValorAtual")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("VALOR_ATUAL");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PLANO", "assinaturas", t =>
                        {
                          t.HasCheckConstraint("CK_PLANO_CODIGO", "length(btrim(\"CODIGO\")) > 0");

                            t.HasCheckConstraint("CK_PLANO_DESCRICAO", "length(btrim(\"DESCRICAO\")) > 0");

                            t.HasCheckConstraint("CK_PLANO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PLANO_MOEDA", "length(btrim(\"MOEDA\")) > 0");

                            t.HasCheckConstraint("CK_PLANO_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_PLANO_PACOTE_ACESSO_CODIGO", "length(btrim(\"PACOTE_ACESSO_CODIGO\")) > 0");

                            t.HasCheckConstraint("CK_PLANO_PERIODICIDADE", "\"PERIODICIDADE\" IN (1, 2)");

                            t.HasCheckConstraint("CK_PLANO_VALOR_ATUAL", "\"VALOR_ATUAL\" >= 0.01 AND \"VALOR_ATUAL\" <= 999999999999.99");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.Assinatura", b =>
                {
                  b.HasOne("Verum.Modules.Assinaturas.Dominio.Plano", "Plano")
                        .WithMany("Assinaturas")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verum.Modules.Assinaturas.Dominio.ClienteGateway", "ClienteGateway")
                        .WithMany("Assinaturas")
                        .HasForeignKey("ClienteGatewayId", "ContaId", "Gateway")
                        .HasPrincipalKey("Id", "ContaId", "Gateway")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteGateway");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.Pagamento", b =>
                {
                  b.HasOne("Verum.Modules.Assinaturas.Dominio.Assinatura", "Assinatura")
                        .WithMany("Pagamentos")
                        .HasForeignKey("AssinaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assinatura");
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.Assinatura", b =>
                {
                  b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.ClienteGateway", b =>
                {
                  b.Navigation("Assinaturas");
                });

            modelBuilder.Entity("Verum.Modules.Assinaturas.Dominio.Plano", b =>
                {
                  b.Navigation("Assinaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
