// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Busca.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Busca.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(BuscaDbContext))]
    partial class BuscaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("busca")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.Busca", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CHAVE_IDEMPOTENCIA");

                    b.Property<string>("CodigoErro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CODIGO_ERRO");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CONCLUIDA_EM");

                    b.Property<string>("ConsultaEstruturada")
                        .HasColumnType("jsonb")
                        .HasColumnName("CONSULTA_ESTRUTURADA");

                    b.Property<string>("ConsultaNormalizada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CONSULTA_NORMALIZADA");

                    b.Property<string>("ConsultaOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CONSULTA_ORIGINAL");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<short>("EtapaAtual")
                        .HasColumnType("smallint")
                        .HasColumnName("ETAPA_ATUAL");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXPIRA_EM");

                    b.Property<DateTimeOffset>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("INICIADA_EM");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("MENSAGEM_ERRO");

                    b.Property<short?>("MotivoSemResultado")
                        .HasColumnType("smallint")
                        .HasColumnName("MOTIVO_SEM_RESULTADO");

                    b.Property<Guid?>("ProdutoPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_PRINCIPAL_ID");

                    b.Property<Guid?>("ProdutoVariantePrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_VARIANTE_PRINCIPAL_ID");

                    b.Property<int>("QuantidadeFontesComFalha")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_FONTES_COM_FALHA");

                    b.Property<int>("QuantidadeFontesComSucesso")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_FONTES_COM_SUCESSO");

                    b.Property<int>("QuantidadeFontesConsultadas")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_FONTES_CONSULTADAS");

                    b.Property<bool>("ResultadoParcial")
                        .HasColumnType("boolean")
                        .HasColumnName("RESULTADO_PARCIAL");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<Guid?>("VisitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("VISITANTE_ID");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "ChaveIdempotencia")
                        .IsUnique()
                        .HasFilter("\"CONTA_ID\" IS NOT NULL");

                    b.HasIndex("VisitanteId", "ChaveIdempotencia")
                        .IsUnique()
                        .HasFilter("\"VISITANTE_ID\" IS NOT NULL");

                    b.ToTable("BUSCA", "busca", t =>
                        {
                          t.HasCheckConstraint("CK_BUSCA_CHAVE_IDEMPOTENCIA", "length(btrim(\"CHAVE_IDEMPOTENCIA\")) > 0");

                            t.HasCheckConstraint("CK_BUSCA_CODIGO_ERRO", "length(btrim(\"CODIGO_ERRO\")) > 0");

                            t.HasCheckConstraint("CK_BUSCA_CONSULTA_ESTRUTURADA", "jsonb_typeof(\"CONSULTA_ESTRUTURADA\") = 'object'");

                            t.HasCheckConstraint("CK_BUSCA_CONSULTA_NORMALIZADA", "length(btrim(\"CONSULTA_NORMALIZADA\")) > 0");

                            t.HasCheckConstraint("CK_BUSCA_CONSULTA_ORIGINAL", "length(btrim(\"CONSULTA_ORIGINAL\")) > 0");

                            t.HasCheckConstraint("CK_BUSCA_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BUSCA_ETAPA_ATUAL", "\"ETAPA_ATUAL\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_BUSCA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BUSCA_MENSAGEM_ERRO", "length(btrim(\"MENSAGEM_ERRO\")) > 0");

                            t.HasCheckConstraint("CK_BUSCA_MOTIVO_SEM_RESULTADO", "\"MOTIVO_SEM_RESULTADO\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_BUSCA_PRODUTO_PRINCIPAL_ID", "\"PRODUTO_PRINCIPAL_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BUSCA_PRODUTO_VARIANTE_PRINCIPAL_ID", "\"PRODUTO_VARIANTE_PRINCIPAL_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BUSCA_QUANTIDADE_FONTES_COM_FALHA", "\"QUANTIDADE_FONTES_COM_FALHA\" >= 0 AND \"QUANTIDADE_FONTES_COM_FALHA\" <= 2147483647");

                            t.HasCheckConstraint("CK_BUSCA_QUANTIDADE_FONTES_COM_SUCESSO", "\"QUANTIDADE_FONTES_COM_SUCESSO\" >= 0 AND \"QUANTIDADE_FONTES_COM_SUCESSO\" <= 2147483647");

                            t.HasCheckConstraint("CK_BUSCA_QUANTIDADE_FONTES_CONSULTADAS", "\"QUANTIDADE_FONTES_CONSULTADAS\" >= 0 AND \"QUANTIDADE_FONTES_CONSULTADAS\" <= 2147483647");

                            t.HasCheckConstraint("CK_BUSCA_REGRA_17", "(\"CONTA_ID\" IS NULL) <> (\"VISITANTE_ID\" IS NULL)");

                            t.HasCheckConstraint("CK_BUSCA_REGRA_18", "\"EXPIRA_EM\" > \"INICIADA_EM\"");

                            t.HasCheckConstraint("CK_BUSCA_STATUS", "\"STATUS\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_BUSCA_VISITANTE_ID", "\"VISITANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.BuscaEtapa", b =>
                {
                  b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BuscaId")
                        .HasColumnType("uuid")
                        .HasColumnName("BUSCA_ID");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CONCLUIDA_EM");

                    b.Property<string>("Detalhes")
                        .HasColumnType("jsonb")
                        .HasColumnName("DETALHES");

                    b.Property<short>("Etapa")
                        .HasColumnType("smallint")
                        .HasColumnName("ETAPA");

                    b.Property<DateTimeOffset>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("INICIADA_EM");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("BuscaId");

                    b.ToTable("BUSCA_ETAPA", "busca", t =>
                        {
                          t.HasCheckConstraint("CK_BUSCA_ETAPA_BUSCA_ID", "\"BUSCA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BUSCA_ETAPA_DETALHES", "jsonb_typeof(\"DETALHES\") = 'object'");

                            t.HasCheckConstraint("CK_BUSCA_ETAPA_ETAPA", "\"ETAPA\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_BUSCA_ETAPA_STATUS", "\"STATUS\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.ResultadoBusca", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid>("BuscaId")
                        .HasColumnType("uuid")
                        .HasColumnName("BUSCA_ID");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GERADO_EM");

                    b.Property<bool>("Parcial")
                        .HasColumnType("boolean")
                        .HasColumnName("PARCIAL");

                    b.Property<int>("QuantidadeAnalisada")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_ANALISADA");

                    b.Property<int>("QuantidadeExibida")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_EXIBIDA");

                    b.Property<string>("VersaoRanking")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("VERSAO_RANKING");

                    b.HasKey("Id");

                    b.HasIndex("BuscaId")
                        .IsUnique();

                    b.ToTable("RESULTADO_BUSCA", "busca", t =>
                        {
                          t.HasCheckConstraint("CK_RESULTADO_BUSCA_BUSCA_ID", "\"BUSCA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_RESULTADO_BUSCA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_RESULTADO_BUSCA_QUANTIDADE_ANALISADA", "\"QUANTIDADE_ANALISADA\" >= 0 AND \"QUANTIDADE_ANALISADA\" <= 2147483647");

                            t.HasCheckConstraint("CK_RESULTADO_BUSCA_QUANTIDADE_EXIBIDA", "\"QUANTIDADE_EXIBIDA\" >= 0 AND \"QUANTIDADE_EXIBIDA\" <= 2147483647");

                            t.HasCheckConstraint("CK_RESULTADO_BUSCA_REGRA_5", "\"QUANTIDADE_EXIBIDA\" <= \"QUANTIDADE_ANALISADA\"");

                            t.HasCheckConstraint("CK_RESULTADO_BUSCA_VERSAO_RANKING", "length(btrim(\"VERSAO_RANKING\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.ResultadoOferta", b =>
                {
                  b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Classificacao")
                        .HasColumnType("smallint")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("EXPLICACAO");

                    b.Property<Guid>("OfertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("OFERTA_ID");

                    b.Property<string>("OfertaSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("OFERTA_SNAPSHOT");

                    b.Property<decimal>("PontuacaoAtualizacao")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PONTUACAO_ATUALIZACAO");

                    b.Property<decimal>("PontuacaoConfianca")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PONTUACAO_CONFIANCA");

                    b.Property<decimal>("PontuacaoFinal")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PONTUACAO_FINAL");

                    b.Property<decimal>("PontuacaoPreco")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PONTUACAO_PRECO");

                    b.Property<short>("Posicao")
                        .HasColumnType("smallint")
                        .HasColumnName("POSICAO");

                    b.Property<Guid>("ProdutoVarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_VARIANTE_ID");

                    b.Property<Guid>("ResultadoBuscaId")
                        .HasColumnType("uuid")
                        .HasColumnName("RESULTADO_BUSCA_ID");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoBuscaId", "Posicao")
                        .IsUnique();

                    b.ToTable("RESULTADO_OFERTA", "busca", t =>
                        {
                          t.HasCheckConstraint("CK_RESULTADO_OFERTA_CLASSIFICACAO", "\"CLASSIFICACAO\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_EXPLICACAO", "length(btrim(\"EXPLICACAO\")) > 0");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_OFERTA_ID", "\"OFERTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_OFERTA_SNAPSHOT", "jsonb_typeof(\"OFERTA_SNAPSHOT\") = 'object'");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_PONTUACAO_ATUALIZACAO", "\"PONTUACAO_ATUALIZACAO\" >= 0 AND \"PONTUACAO_ATUALIZACAO\" <= 100");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_PONTUACAO_CONFIANCA", "\"PONTUACAO_CONFIANCA\" >= 0 AND \"PONTUACAO_CONFIANCA\" <= 100");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_PONTUACAO_FINAL", "\"PONTUACAO_FINAL\" >= 0 AND \"PONTUACAO_FINAL\" <= 100");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_PONTUACAO_PRECO", "\"PONTUACAO_PRECO\" >= 0 AND \"PONTUACAO_PRECO\" <= 100");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_POSICAO", "\"POSICAO\" >= 1 AND \"POSICAO\" <= 32767");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_PRODUTO_VARIANTE_ID", "\"PRODUTO_VARIANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_RESULTADO_OFERTA_RESULTADO_BUSCA_ID", "\"RESULTADO_BUSCA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.BuscaEtapa", b =>
                {
                  b.HasOne("Verum.Modules.Busca.Dominio.Busca", "Busca")
                        .WithMany("Etapas")
                        .HasForeignKey("BuscaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Busca");
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.ResultadoBusca", b =>
                {
                  b.HasOne("Verum.Modules.Busca.Dominio.Busca", "Busca")
                        .WithOne("Resultado")
                        .HasForeignKey("Verum.Modules.Busca.Dominio.ResultadoBusca", "BuscaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Busca");
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.ResultadoOferta", b =>
                {
                  b.HasOne("Verum.Modules.Busca.Dominio.ResultadoBusca", "Resultado")
                        .WithMany("Ofertas")
                        .HasForeignKey("ResultadoBuscaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.Busca", b =>
                {
                  b.Navigation("Etapas");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("Verum.Modules.Busca.Dominio.ResultadoBusca", b =>
                {
                  b.Navigation("Ofertas");
                });
#pragma warning restore 612, 618
        }
    }
}
