<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <InternalsVisibleTo Include="Verum.Tests.Integracao" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Verum.BuildingBlocks/Verum.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>