<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <ProjectReference Include="../../Verum.CrossCutting/Verum.CrossCutting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Verum.BuildingBlocks/Verum.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
