<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Modules/Verum.Modules.Busca/Verum.Modules.Busca.csproj" />
    <ProjectReference Include="../Modules/Verum.Modules.Catalogo/Verum.Modules.Catalogo.csproj" />
    <ProjectReference Include="../Modules/Verum.Modules.Ofertas/Verum.Modules.Ofertas.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Modules/Verum.Modules.Contas/Verum.Modules.Contas.csproj" />
    <ProjectReference Include="../Modules/Verum.Modules.Radar/Verum.Modules.Radar.csproj" />
    <ProjectReference Include="../Modules/Verum.Modules.Notificacoes/Verum.Modules.Notificacoes.csproj" />
    <ProjectReference Include="../Modules/Verum.Modules.Acesso/Verum.Modules.Acesso.csproj" />
    <ProjectReference Include="../Modules/Verum.Modules.Assinaturas/Verum.Modules.Assinaturas.csproj" />
  </ItemGroup>
</Project>
