<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <ProjectReference Include="../../Verum.CrossCutting/Verum.CrossCutting.csproj" />
    <ProjectReference Include="../../Apps/Verum.Api/Verum.Api.csproj" Aliases="global,VerumApi" />
    <ProjectReference Include="../../Apps/Verum.Worker.Descoberta/Verum.Worker.Descoberta.csproj" />
    <ProjectReference Include="../../Apps/Verum.Worker.Radar/Verum.Worker.Radar.csproj" />
  </ItemGroup>
</Project>
