// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Contas.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Contas.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(ContasDbContext))]
    partial class ContasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contas")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Contas.Dominio.Conta", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTimeOffset?>("ExcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXCLUIDA_EM");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOME_EXIBICAO");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<string>("SujeitoIdentidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SUJEITO_IDENTIDADE");

                    b.HasKey("Id");

                    b.HasIndex("SujeitoIdentidade")
                        .IsUnique();

                    b.ToTable("CONTA", "contas", t =>
                        {
                          t.HasCheckConstraint("CK_CONTA_EMAIL", "length(btrim(\"EMAIL\")) > 0");

                            t.HasCheckConstraint("CK_CONTA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CONTA_NOME_EXIBICAO", "length(btrim(\"NOME_EXIBICAO\")) > 0");

                            t.HasCheckConstraint("CK_CONTA_STATUS", "\"STATUS\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_CONTA_SUJEITO_IDENTIDADE", "length(btrim(\"SUJEITO_IDENTIDADE\")) > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
