// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Ofertas.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Ofertas.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(OfertasDbContext))]
    [Migration("20260926134527_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ofertas")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.ExecucaoConsultaFonte", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid>("BuscaId")
                        .HasColumnType("uuid")
                        .HasColumnName("BUSCA_ID");

                    b.Property<string>("CodigoErro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CODIGO_ERRO");

                    b.Property<Guid>("CorrelacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("CORRELACAO_ID");

                    b.Property<string>("DetalhesErro")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("DETALHES_ERRO");

                    b.Property<DateTimeOffset?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FINALIZADA_EM");

                    b.Property<Guid>("FonteOfertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("FONTE_OFERTA_ID");

                    b.Property<DateTimeOffset>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("INICIADA_EM");

                    b.Property<short>("NumeroTentativas")
                        .HasColumnType("smallint")
                        .HasColumnName("NUMERO_TENTATIVAS");

                    b.Property<int>("QuantidadeItensAceitos")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_ITENS_ACEITOS");

                    b.Property<int>("QuantidadeItensEncontrados")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE_ITENS_ENCONTRADOS");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<short>("TipoProvedor")
                        .HasColumnType("smallint")
                        .HasColumnName("TIPO_PROVEDOR");

                    b.HasKey("Id");

                    b.HasIndex("FonteOfertaId");

                    b.ToTable("EXECUCAO_CONSULTA_FONTE", "ofertas", t =>
                        {
                          t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_BUSCA_ID", "\"BUSCA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_CODIGO_ERRO", "length(btrim(\"CODIGO_ERRO\")) > 0");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_CORRELACAO_ID", "\"CORRELACAO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_DETALHES_ERRO", "length(btrim(\"DETALHES_ERRO\")) > 0");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_FONTE_OFERTA_ID", "\"FONTE_OFERTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_NUMERO_TENTATIVAS", "\"NUMERO_TENTATIVAS\" >= 0 AND \"NUMERO_TENTATIVAS\" <= 32767");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_QUANTIDADE_ITENS_ACEITOS", "\"QUANTIDADE_ITENS_ACEITOS\" >= 0 AND \"QUANTIDADE_ITENS_ACEITOS\" <= 2147483647");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_QUANTIDADE_ITENS_ENCONTRADOS", "\"QUANTIDADE_ITENS_ENCONTRADOS\" >= 0 AND \"QUANTIDADE_ITENS_ENCONTRADOS\" <= 2147483647");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_STATUS", "\"STATUS\" IN (1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("CK_EXECUCAO_CONSULTA_FONTE_TIPO_PROVEDOR", "\"TIPO_PROVEDOR\" IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.FonteOferta", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ATIVA");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<decimal>("NivelConfianca")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("NIVEL_CONFIANCA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("NOME");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("FONTE_OFERTA", "ofertas", t =>
                        {
                          t.HasCheckConstraint("CK_FONTE_OFERTA_CODIGO", "length(btrim(\"CODIGO\")) > 0");

                            t.HasCheckConstraint("CK_FONTE_OFERTA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_FONTE_OFERTA_NIVEL_CONFIANCA", "\"NIVEL_CONFIANCA\" >= 0 AND \"NIVEL_CONFIANCA\" <= 100");

                            t.HasCheckConstraint("CK_FONTE_OFERTA_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_FONTE_OFERTA_TIPO", "\"TIPO\" IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.Loja", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Dominio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DOMINIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("NOME_NORMALIZADO");

                    b.Property<decimal>("PontuacaoConfianca")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PONTUACAO_CONFIANCA");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("URL");

                    b.Property<bool>("Verificada")
                        .HasColumnType("boolean")
                        .HasColumnName("VERIFICADA");

                    b.HasKey("Id");

                    b.ToTable("LOJA", "ofertas", t =>
                        {
                          t.HasCheckConstraint("CK_LOJA_DOMINIO", "length(btrim(\"DOMINIO\")) > 0");

                            t.HasCheckConstraint("CK_LOJA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_LOJA_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_LOJA_NOME_NORMALIZADO", "length(btrim(\"NOME_NORMALIZADO\")) > 0");

                            t.HasCheckConstraint("CK_LOJA_PONTUACAO_CONFIANCA", "\"PONTUACAO_CONFIANCA\" >= 0 AND \"PONTUACAO_CONFIANCA\" <= 100");

                            t.HasCheckConstraint("CK_LOJA_STATUS", "\"STATUS\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_LOJA_URL", "length(btrim(\"URL\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.Oferta", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<string>("CondicaoPreco")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("CONDICAO_PRECO");

                    b.Property<short>("CondicaoProduto")
                        .HasColumnType("smallint")
                        .HasColumnName("CONDICAO_PRODUTO");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<short>("Disponibilidade")
                        .HasColumnType("smallint")
                        .HasColumnName("DISPONIBILIDADE");

                    b.Property<Guid>("FonteId")
                        .HasColumnType("uuid")
                        .HasColumnName("FONTE_ID");

                    b.Property<string>("IdentificadorExterno")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("IDENTIFICADOR_EXTERNO");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("text")
                        .HasColumnName("IMAGEM_URL");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("LOJA_ID");

                    b.Property<DateTimeOffset>("ObservadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OBSERVADA_EM");

                    b.Property<decimal?>("PrecoAnterior")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_ANTERIOR");

                    b.Property<decimal>("PrecoAtual")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_ATUAL");

                    b.Property<decimal?>("PrecoPix")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_PIX");

                    b.Property<Guid>("ProdutoVarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_VARIANTE_ID");

                    b.Property<short?>("QuantidadeParcelas")
                        .HasColumnType("smallint")
                        .HasColumnName("QUANTIDADE_PARCELAS");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<string>("TituloExterno")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TITULO_EXTERNO");

                    b.Property<DateTimeOffset>("UltimaConfirmacaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ULTIMA_CONFIRMACAO_EM");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("URL");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("URL_HASH");

                    b.Property<DateTimeOffset>("ValidaAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VALIDA_ATE");

                    b.Property<decimal?>("ValorParcela")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("VALOR_PARCELA");

                    b.HasKey("Id");

                    b.HasIndex("FonteId");

                    b.HasIndex("LojaId", "UrlHash")
                        .IsUnique();

                    b.ToTable("OFERTA", "ofertas", t =>
                        {
                          t.HasCheckConstraint("CK_OFERTA_CONDICAO_PRECO", "length(btrim(\"CONDICAO_PRECO\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_CONDICAO_PRODUTO", "\"CONDICAO_PRODUTO\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OFERTA_DISPONIBILIDADE", "\"DISPONIBILIDADE\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OFERTA_FONTE_ID", "\"FONTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OFERTA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OFERTA_IDENTIFICADOR_EXTERNO", "length(btrim(\"IDENTIFICADOR_EXTERNO\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_IMAGEM_URL", "length(btrim(\"IMAGEM_URL\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_LOJA_ID", "\"LOJA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OFERTA_PRECO_ANTERIOR", "\"PRECO_ANTERIOR\" >= 0.01 AND \"PRECO_ANTERIOR\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OFERTA_PRECO_ATUAL", "\"PRECO_ATUAL\" >= 0.01 AND \"PRECO_ATUAL\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OFERTA_PRECO_PIX", "\"PRECO_PIX\" >= 0.01 AND \"PRECO_PIX\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OFERTA_PRODUTO_VARIANTE_ID", "\"PRODUTO_VARIANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OFERTA_QUANTIDADE_PARCELAS", "\"QUANTIDADE_PARCELAS\" >= 1 AND \"QUANTIDADE_PARCELAS\" <= 32767");

                            t.HasCheckConstraint("CK_OFERTA_REGRA_18", "\"VALIDA_ATE\" > \"OBSERVADA_EM\"");

                            t.HasCheckConstraint("CK_OFERTA_REGRA_19", "(\"QUANTIDADE_PARCELAS\" IS NULL) = (\"VALOR_PARCELA\" IS NULL)");

                            t.HasCheckConstraint("CK_OFERTA_STATUS", "\"STATUS\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OFERTA_TITULO_EXTERNO", "length(btrim(\"TITULO_EXTERNO\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_URL", "length(btrim(\"URL\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_URL_HASH", "length(btrim(\"URL_HASH\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_VALOR_PARCELA", "\"VALOR_PARCELA\" >= 0.01 AND \"VALOR_PARCELA\" <= 999999999999.99");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.OfertaObservacao", b =>
                {
                  b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CondicaoPreco")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("CONDICAO_PRECO");

                    b.Property<short>("Disponibilidade")
                        .HasColumnType("smallint")
                        .HasColumnName("DISPONIBILIDADE");

                    b.Property<string>("Evidencia")
                        .HasColumnType("jsonb")
                        .HasColumnName("EVIDENCIA");

                    b.Property<Guid>("FonteId")
                        .HasColumnType("uuid")
                        .HasColumnName("FONTE_ID");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("HASH_CONTEUDO");

                    b.Property<DateTimeOffset>("ObservadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OBSERVADA_EM");

                    b.Property<Guid>("OfertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("OFERTA_ID");

                    b.Property<decimal>("Preco")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO");

                    b.Property<decimal?>("PrecoPix")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("PRECO_PIX");

                    b.Property<short?>("QuantidadeParcelas")
                        .HasColumnType("smallint")
                        .HasColumnName("QUANTIDADE_PARCELAS");

                    b.Property<decimal?>("ValorParcela")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("VALOR_PARCELA");

                    b.HasKey("Id");

                    b.HasIndex("FonteId");

                    b.HasIndex("OfertaId");

                    b.ToTable("OFERTA_OBSERVACAO", "ofertas", t =>
                        {
                          t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_CONDICAO_PRECO", "length(btrim(\"CONDICAO_PRECO\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_DISPONIBILIDADE", "\"DISPONIBILIDADE\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_EVIDENCIA", "jsonb_typeof(\"EVIDENCIA\") = 'object'");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_FONTE_ID", "\"FONTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_HASH_CONTEUDO", "length(btrim(\"HASH_CONTEUDO\")) > 0");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_OFERTA_ID", "\"OFERTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_PRECO", "\"PRECO\" >= 0.01 AND \"PRECO\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_PRECO_PIX", "\"PRECO_PIX\" >= 0.01 AND \"PRECO_PIX\" <= 999999999999.99");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_QUANTIDADE_PARCELAS", "\"QUANTIDADE_PARCELAS\" >= 1 AND \"QUANTIDADE_PARCELAS\" <= 32767");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_REGRA_10", "(\"QUANTIDADE_PARCELAS\" IS NULL) = (\"VALOR_PARCELA\" IS NULL)");

                            t.HasCheckConstraint("CK_OFERTA_OBSERVACAO_VALOR_PARCELA", "\"VALOR_PARCELA\" >= 0.01 AND \"VALOR_PARCELA\" <= 999999999999.99");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.ExecucaoConsultaFonte", b =>
                {
                  b.HasOne("Verum.Modules.Ofertas.Dominio.FonteOferta", "Fonte")
                        .WithMany("Execucoes")
                        .HasForeignKey("FonteOfertaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fonte");
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.Oferta", b =>
                {
                  b.HasOne("Verum.Modules.Ofertas.Dominio.FonteOferta", "Fonte")
                        .WithMany("Ofertas")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verum.Modules.Ofertas.Dominio.Loja", "Loja")
                        .WithMany("Ofertas")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fonte");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.OfertaObservacao", b =>
                {
                  b.HasOne("Verum.Modules.Ofertas.Dominio.FonteOferta", "Fonte")
                        .WithMany("Observacoes")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verum.Modules.Ofertas.Dominio.Oferta", "Oferta")
                        .WithMany("Observacoes")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fonte");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.FonteOferta", b =>
                {
                  b.Navigation("Execucoes");

                    b.Navigation("Observacoes");

                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.Loja", b =>
                {
                  b.Navigation("Ofertas");
                });

            modelBuilder.Entity("Verum.Modules.Ofertas.Dominio.Oferta", b =>
                {
                  b.Navigation("Observacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
