// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Catalogo.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Catalogo.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(CatalogoDbContext))]
    partial class CatalogoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogo")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Categoria", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ATIVA");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("CATEGORIA_PAI_ID");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("NOME");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)")
                        .HasColumnName("SLUG");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CATEGORIA", "catalogo", t =>
                        {
                          t.HasCheckConstraint("CK_CATEGORIA_CATEGORIA_PAI_ID", "\"CATEGORIA_PAI_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CATEGORIA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CATEGORIA_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_CATEGORIA_REGRA_4", "\"CATEGORIA_PAI_ID\" IS NULL OR \"CATEGORIA_PAI_ID\" <> \"ID\"");

                            t.HasCheckConstraint("CK_CATEGORIA_SLUG", "length(btrim(\"SLUG\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Marca", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ATIVA");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("NOME_NORMALIZADO");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)")
                        .HasColumnName("SLUG");

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("MARCA", "catalogo", t =>
                        {
                          t.HasCheckConstraint("CK_MARCA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_MARCA_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_MARCA_NOME_NORMALIZADO", "length(btrim(\"NOME_NORMALIZADO\")) > 0");

                            t.HasCheckConstraint("CK_MARCA_SLUG", "length(btrim(\"SLUG\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Produto", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("Atributos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ATRIBUTOS");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADO_EM");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("DESCRICAO");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("uuid")
                        .HasColumnName("MARCA_ID");

                    b.Property<string>("Modelo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME_NORMALIZADO");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("varchar(280)")
                        .HasColumnName("SLUG");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PRODUTO", "catalogo", t =>
                        {
                          t.HasCheckConstraint("CK_PRODUTO_ATRIBUTOS", "jsonb_typeof(\"ATRIBUTOS\") = 'object'");

                            t.HasCheckConstraint("CK_PRODUTO_CATEGORIA_ID", "\"CATEGORIA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_DESCRICAO", "length(btrim(\"DESCRICAO\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_MARCA_ID", "\"MARCA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_MODELO", "length(btrim(\"MODELO\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_NOME_NORMALIZADO", "length(btrim(\"NOME_NORMALIZADO\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_SLUG", "length(btrim(\"SLUG\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_STATUS", "\"STATUS\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoIdentificador", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<Guid>("ProdutoVarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_VARIANTE_ID");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("TIPO");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoVarianteId");

                    b.HasIndex("Tipo", "Valor")
                        .IsUnique();

                    b.ToTable("PRODUTO_IDENTIFICADOR", "catalogo", t =>
                        {
                          t.HasCheckConstraint("CK_PRODUTO_IDENTIFICADOR_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_IDENTIFICADOR_PRODUTO_VARIANTE_ID", "\"PRODUTO_VARIANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_IDENTIFICADOR_TIPO", "\"TIPO\" IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_PRODUTO_IDENTIFICADOR_VALOR", "length(btrim(\"VALOR\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoImagem", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ORDEM");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ORIGEM");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("PRINCIPAL");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<Guid?>("ProdutoVarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_VARIANTE_ID");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoVarianteId", "ProdutoId");

                    b.ToTable("PRODUTO_IMAGEM", "catalogo", t =>
                        {
                          t.HasCheckConstraint("CK_PRODUTO_IMAGEM_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_IMAGEM_ORDEM", "\"ORDEM\" >= 0 AND \"ORDEM\" <= 32767");

                            t.HasCheckConstraint("CK_PRODUTO_IMAGEM_ORIGEM", "length(btrim(\"ORIGEM\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_IMAGEM_PRODUTO_ID", "\"PRODUTO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_IMAGEM_PRODUTO_VARIANTE_ID", "\"PRODUTO_VARIANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_IMAGEM_URL", "length(btrim(\"URL\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoTermoBusca", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<decimal>("Confianca")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("CONFIANCA");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<short>("Origem")
                        .HasColumnType("smallint")
                        .HasColumnName("ORIGEM");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<Guid?>("ProdutoVarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_VARIANTE_ID");

                    b.Property<string>("TermoNormalizado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("TERMO_NORMALIZADO");

                    b.Property<string>("TermoOriginal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("TERMO_ORIGINAL");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoVarianteId", "ProdutoId");

                    b.ToTable("PRODUTO_TERMO_BUSCA", "catalogo", t =>
                        {
                          t.HasCheckConstraint("CK_PRODUTO_TERMO_BUSCA_CONFIANCA", "\"CONFIANCA\" >= 0 AND \"CONFIANCA\" <= 1");

                            t.HasCheckConstraint("CK_PRODUTO_TERMO_BUSCA_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_TERMO_BUSCA_ORIGEM", "\"ORIGEM\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_PRODUTO_TERMO_BUSCA_PRODUTO_ID", "\"PRODUTO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_TERMO_BUSCA_PRODUTO_VARIANTE_ID", "\"PRODUTO_VARIANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_TERMO_BUSCA_TERMO_NORMALIZADO", "length(btrim(\"TERMO_NORMALIZADO\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_TERMO_BUSCA_TERMO_ORIGINAL", "length(btrim(\"TERMO_ORIGINAL\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoVariante", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("Atributos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ATRIBUTOS");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("NOME_NORMALIZADO");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("SLUG");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PRODUTO_VARIANTE", "catalogo", t =>
                        {
                          t.HasCheckConstraint("CK_PRODUTO_VARIANTE_ATRIBUTOS", "jsonb_typeof(\"ATRIBUTOS\") = 'object'");

                            t.HasCheckConstraint("CK_PRODUTO_VARIANTE_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_VARIANTE_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_VARIANTE_NOME_NORMALIZADO", "length(btrim(\"NOME_NORMALIZADO\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_VARIANTE_PRODUTO_ID", "\"PRODUTO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PRODUTO_VARIANTE_SLUG", "length(btrim(\"SLUG\")) > 0");

                            t.HasCheckConstraint("CK_PRODUTO_VARIANTE_STATUS", "\"STATUS\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Categoria", b =>
                {
                  b.HasOne("Verum.Modules.Catalogo.Dominio.Categoria", "CategoriaPai")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Produto", b =>
                {
                  b.HasOne("Verum.Modules.Catalogo.Dominio.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verum.Modules.Catalogo.Dominio.Marca", "Marca")
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoIdentificador", b =>
                {
                  b.HasOne("Verum.Modules.Catalogo.Dominio.ProdutoVariante", "Variante")
                        .WithMany("Identificadores")
                        .HasForeignKey("ProdutoVarianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoImagem", b =>
                {
                  b.HasOne("Verum.Modules.Catalogo.Dominio.Produto", "Produto")
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verum.Modules.Catalogo.Dominio.ProdutoVariante", "Variante")
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutoVarianteId", "ProdutoId")
                        .HasPrincipalKey("Id", "ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Produto");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoTermoBusca", b =>
                {
                  b.HasOne("Verum.Modules.Catalogo.Dominio.Produto", "Produto")
                        .WithMany("TermosBusca")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verum.Modules.Catalogo.Dominio.ProdutoVariante", "Variante")
                        .WithMany("TermosBusca")
                        .HasForeignKey("ProdutoVarianteId", "ProdutoId")
                        .HasPrincipalKey("Id", "ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Produto");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoVariante", b =>
                {
                  b.HasOne("Verum.Modules.Catalogo.Dominio.Produto", "Produto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Categoria", b =>
                {
                  b.Navigation("Produtos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Marca", b =>
                {
                  b.Navigation("Produtos");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.Produto", b =>
                {
                  b.Navigation("Imagens");

                    b.Navigation("TermosBusca");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("Verum.Modules.Catalogo.Dominio.ProdutoVariante", b =>
                {
                  b.Navigation("Identificadores");

                    b.Navigation("Imagens");

                    b.Navigation("TermosBusca");
                });
#pragma warning restore 612, 618
        }
    }
}
