// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Notificacoes.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Notificacoes.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(NotificacoesDbContext))]
    partial class NotificacoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notificacoes")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Notificacoes.Dominio.EntregaNotificacao", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<short>("Canal")
                        .HasColumnType("smallint")
                        .HasColumnName("CANAL");

                    b.Property<string>("CodigoErro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CODIGO_ERRO");

                    b.Property<string>("DetalhesErro")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("DETALHES_ERRO");

                    b.Property<DateTimeOffset?>("EntregueEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ENTREGUE_EM");

                    b.Property<Guid>("NotificacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("NOTIFICACAO_ID");

                    b.Property<DateTimeOffset?>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PROXIMA_TENTATIVA_EM");

                    b.Property<short>("QuantidadeTentativas")
                        .HasColumnType("smallint")
                        .HasColumnName("QUANTIDADE_TENTATIVAS");

                    b.Property<string>("ReferenciaProvedor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("REFERENCIA_PROVEDOR");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<DateTimeOffset?>("UltimaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ULTIMA_TENTATIVA_EM");

                    b.HasKey("Id");

                    b.HasIndex("NotificacaoId", "Canal")
                        .IsUnique();

                    b.ToTable("ENTREGA_NOTIFICACAO", "notificacoes", t =>
                        {
                          t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_CANAL", "\"CANAL\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_CODIGO_ERRO", "length(btrim(\"CODIGO_ERRO\")) > 0");

                            t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_DETALHES_ERRO", "length(btrim(\"DETALHES_ERRO\")) > 0");

                            t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_NOTIFICACAO_ID", "\"NOTIFICACAO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_QUANTIDADE_TENTATIVAS", "\"QUANTIDADE_TENTATIVAS\" >= 0 AND \"QUANTIDADE_TENTATIVAS\" <= 32767");

                            t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_REFERENCIA_PROVEDOR", "length(btrim(\"REFERENCIA_PROVEDOR\")) > 0");

                            t.HasCheckConstraint("CK_ENTREGA_NOTIFICACAO_STATUS", "\"STATUS\" IN (1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Notificacoes.Dominio.Notificacao", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Dados")
                        .HasColumnType("jsonb")
                        .HasColumnName("DADOS");

                    b.Property<DateTimeOffset?>("LidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LIDA_EM");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("TIPO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.ToTable("NOTIFICACAO", "notificacoes", t =>
                        {
                          t.HasCheckConstraint("CK_NOTIFICACAO_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_NOTIFICACAO_DADOS", "jsonb_typeof(\"DADOS\") = 'object'");

                            t.HasCheckConstraint("CK_NOTIFICACAO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_NOTIFICACAO_MENSAGEM", "length(btrim(\"MENSAGEM\")) > 0");

                            t.HasCheckConstraint("CK_NOTIFICACAO_STATUS", "\"STATUS\" IN (1, 2)");

                            t.HasCheckConstraint("CK_NOTIFICACAO_TIPO", "\"TIPO\" IN (1, 2)");

                            t.HasCheckConstraint("CK_NOTIFICACAO_TITULO", "length(btrim(\"TITULO\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Notificacoes.Dominio.PreferenciaNotificacao", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<short>("Canal")
                        .HasColumnType("smallint")
                        .HasColumnName("CANAL");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("boolean")
                        .HasColumnName("HABILITADA");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "Canal")
                        .IsUnique();

                    b.ToTable("PREFERENCIA_NOTIFICACAO", "notificacoes", t =>
                        {
                          t.HasCheckConstraint("CK_PREFERENCIA_NOTIFICACAO_CANAL", "\"CANAL\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_PREFERENCIA_NOTIFICACAO_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PREFERENCIA_NOTIFICACAO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Notificacoes.Dominio.EntregaNotificacao", b =>
                {
                  b.HasOne("Verum.Modules.Notificacoes.Dominio.Notificacao", "Notificacao")
                        .WithMany("Entregas")
                        .HasForeignKey("NotificacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notificacao");
                });

            modelBuilder.Entity("Verum.Modules.Notificacoes.Dominio.Notificacao", b =>
                {
                  b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
