// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verum.Modules.Acesso.Infraestrutura.Persistencia;

#nullable disable

namespace Verum.Modules.Acesso.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(AcessoDbContext))]
    partial class AcessoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acesso")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.ConcessaoPacote", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADA_EM");

                    b.Property<short>("Origem")
                        .HasColumnType("smallint")
                        .HasColumnName("ORIGEM");

                    b.Property<Guid>("PacoteAcessoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PACOTE_ACESSO_ID");

                    b.Property<Guid?>("ReferenciaOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("REFERENCIA_ORIGEM_ID");

                    b.Property<DateTimeOffset?>("RevogadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("REVOGADA_EM");

                    b.Property<DateTimeOffset?>("ValidaAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VALIDA_ATE");

                    b.Property<DateTimeOffset>("ValidaDe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VALIDA_DE");

                    b.HasKey("Id");

                    b.HasIndex("PacoteAcessoId");

                    b.ToTable("CONCESSAO_PACOTE", "acesso", t =>
                        {
                          t.HasCheckConstraint("CK_CONCESSAO_PACOTE_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CONCESSAO_PACOTE_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CONCESSAO_PACOTE_ORIGEM", "\"ORIGEM\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_CONCESSAO_PACOTE_PACOTE_ACESSO_ID", "\"PACOTE_ACESSO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CONCESSAO_PACOTE_REFERENCIA_ORIGEM_ID", "\"REFERENCIA_ORIGEM_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CONCESSAO_PACOTE_REGRA_5", "\"VALIDA_ATE\" IS NULL OR \"VALIDA_ATE\" > \"VALIDA_DE\"");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.PacoteAcesso", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ATIVO");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATUALIZADO_EM");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PACOTE_ACESSO", "acesso", t =>
                        {
                          t.HasCheckConstraint("CK_PACOTE_ACESSO_CODIGO", "length(btrim(\"CODIGO\")) > 0");

                            t.HasCheckConstraint("CK_PACOTE_ACESSO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PACOTE_ACESSO_NOME", "length(btrim(\"NOME\")) > 0");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.PacoteRecurso", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("Configuracao")
                        .HasColumnType("jsonb")
                        .HasColumnName("CONFIGURACAO");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("HABILITADO");

                    b.Property<int?>("LimiteQuantidade")
                        .HasColumnType("integer")
                        .HasColumnName("LIMITE_QUANTIDADE");

                    b.Property<Guid>("PacoteAcessoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PACOTE_ACESSO_ID");

                    b.Property<short?>("Periodicidade")
                        .HasColumnType("smallint")
                        .HasColumnName("PERIODICIDADE");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("RECURSO_ID");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("PacoteAcessoId", "RecursoId")
                        .IsUnique();

                    b.ToTable("PACOTE_RECURSO", "acesso", t =>
                        {
                          t.HasCheckConstraint("CK_PACOTE_RECURSO_CONFIGURACAO", "jsonb_typeof(\"CONFIGURACAO\") = 'object'");

                            t.HasCheckConstraint("CK_PACOTE_RECURSO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PACOTE_RECURSO_LIMITE_QUANTIDADE", "\"LIMITE_QUANTIDADE\" >= 0 AND \"LIMITE_QUANTIDADE\" <= 2147483647");

                            t.HasCheckConstraint("CK_PACOTE_RECURSO_PACOTE_ACESSO_ID", "\"PACOTE_ACESSO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_PACOTE_RECURSO_PERIODICIDADE", "\"PERIODICIDADE\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_PACOTE_RECURSO_RECURSO_ID", "\"RECURSO_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.Recurso", b =>
                {
                  b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOME");

                    b.Property<short>("TipoLimite")
                        .HasColumnType("smallint")
                        .HasColumnName("TIPO_LIMITE");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RECURSO", "acesso", t =>
                        {
                          t.HasCheckConstraint("CK_RECURSO_CODIGO", "length(btrim(\"CODIGO\")) > 0");

                            t.HasCheckConstraint("CK_RECURSO_DESCRICAO", "length(btrim(\"DESCRICAO\")) > 0");

                            t.HasCheckConstraint("CK_RECURSO_ID", "\"ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_RECURSO_NOME", "length(btrim(\"NOME\")) > 0");

                            t.HasCheckConstraint("CK_RECURSO_TIPO_LIMITE", "\"TIPO_LIMITE\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.RegistroUso", b =>
                {
                  b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTA_ID");

                    b.Property<string>("Dados")
                        .HasColumnType("jsonb")
                        .HasColumnName("DADOS");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OCORRIDO_EM");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("RecursoCodigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RECURSO_CODIGO");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("REFERENCIA_ID");

                    b.Property<Guid?>("VisitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("VISITANTE_ID");

                    b.HasKey("Id");

                    b.ToTable("REGISTRO_USO", "acesso", t =>
                        {
                          t.HasCheckConstraint("CK_REGISTRO_USO_CONTA_ID", "\"CONTA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_REGISTRO_USO_DADOS", "jsonb_typeof(\"DADOS\") = 'object'");

                            t.HasCheckConstraint("CK_REGISTRO_USO_QUANTIDADE", "\"QUANTIDADE\" >= 1 AND \"QUANTIDADE\" <= 2147483647");

                            t.HasCheckConstraint("CK_REGISTRO_USO_RECURSO_CODIGO", "length(btrim(\"RECURSO_CODIGO\")) > 0");

                            t.HasCheckConstraint("CK_REGISTRO_USO_REFERENCIA_ID", "\"REFERENCIA_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_REGISTRO_USO_REGRA_6", "(\"CONTA_ID\" IS NULL) <> (\"VISITANTE_ID\" IS NULL)");

                            t.HasCheckConstraint("CK_REGISTRO_USO_VISITANTE_ID", "\"VISITANTE_ID\" <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.ConcessaoPacote", b =>
                {
                  b.HasOne("Verum.Modules.Acesso.Dominio.PacoteAcesso", "Pacote")
                        .WithMany("Concessoes")
                        .HasForeignKey("PacoteAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.PacoteRecurso", b =>
                {
                  b.HasOne("Verum.Modules.Acesso.Dominio.PacoteAcesso", "Pacote")
                        .WithMany("Recursos")
                        .HasForeignKey("PacoteAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verum.Modules.Acesso.Dominio.Recurso", "Recurso")
                        .WithMany("Pacotes")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pacote");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.PacoteAcesso", b =>
                {
                  b.Navigation("Concessoes");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Verum.Modules.Acesso.Dominio.Recurso", b =>
                {
                  b.Navigation("Pacotes");
                });
#pragma warning restore 612, 618
        }
    }
}
